/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScreenShot {
  displayInfo: DisplayInfo
  imagePath: string
}
export interface DisplayInfo {
  id: number
  x: number
  y: number
  width: number
  height: number
  rotation: number
  scaleFactor: number
  isPrimary: boolean
}
export function sum(a: number, b: number): number
export function screenShots(): void
export function getScreenShotByDisplayInfo(screenShot: ScreenShot): void
export function getScreenShotByteByDisplayInfo(screenShot: ScreenShot): Array<number>
export function getNums(): Array<number>
